vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        evenements:
            uri_prefix: /images/evenements
            upload_destination: '%kernel.project_dir%/public/images/evenements'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
