vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        actualite:
            uri_prefix: /images/actualite
            upload_destination: '%kernel.project_dir%/public/images/actualite'
            namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
